apiVersion: apps/v1
kind: Deployment
metadata:
  name: counterapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counterapp
  template:
    metadata:
      labels:
        app: counterapp
    spec:
      containers:
      - name: counterapp
        image: us-central1-docker.pkg.dev/sunny-cider-459704-j1/democlass2/app:1.0
        ports:
        - containerPort: 8080
