apiVersion: apps/v1
kind: Deployment
metadata:
  name: counterapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counterapp
  template:
    metadata:
      labels:
        app: counterapp
    spec:
      containers:
        - name: counterapp
          image: vbadiger/counterapp:latest
          ports:
            - containerPort: 8080
