apiVersion: v1
kind: Service
metadata:
  name: counterapp-service
spec:
  type: NodePort
  selector:
    app: counterapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
